#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Mei Kondo
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
ansm
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

    try:
        ansm -= int(line)
    except:
        ansm -= float(line)

print(ans, ansm)
