#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Mei Kondo
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
aans = 0
for line in sys.stdin:
    try:
        ans += int(line)
        aans -= int(line)
    except:
        ans += float(line)
        aans -= float(line)

print(ans)
print(aans)
