#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Mei Kondo
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ams += float(line)

print(ans)
